apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: customers-virtual-service-mtls
spec:
  hosts:
  - customers.payments-mtls.svc.cluster.local
  http:
  - route:
    - destination:
        host: customers.payments-mtls.svc.cluster.local
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: customers-destination-rule-mtls
spec:
  host: customers.payments-mtls.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1