apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: facade-virtual-service-mtls
spec:
  hosts:
  - facade.payments-mtls.svc.cluster.local
  http:
  - route:
    - destination:
        host: facade.payments-mtls.svc.cluster.local
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: facade-destination-rule-mtls
spec:
  host: facade.payments-mtls.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL  
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "facade-policy-mtls"
spec:
  targets:
  - name: "facade"
  peers:
  - mtls: {}      