apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: issuer-one-virtual-service-mtls
spec:
  hosts:
  - issuer-one.payments-mtls.svc.cluster.local
  http:
  - route:
    - destination:
        host: issuer-one.payments-mtls.svc.cluster.local
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: issuer-one-destination-rule-mtls
spec:
  host: issuer-one.payments-mtls.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1