apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: payments-virtual-service-mtls
spec:
  hosts:
  - payments.payments-mtls.svc.cluster.local
  http:
  - route:
    - destination:
        host: payments.payments-mtls.svc.cluster.local
        subset: v1
      weight: 100  
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: payments-destination-rule-mtls
spec:
  host: payments.payments-mtls.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1