apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: systems-virtual-service-mtls
spec:
  hosts:
  - systems.payments-mtls.svc.cluster.local
  http:
  - route:
    - destination:
        host: systems.payments-mtls.svc.cluster.local
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: systems-destination-rule-mtls
spec:
  host: systems.payments-mtls.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "systems-policy-mtls"
spec:
  targets:
  - name: systems
  peers:
  - mtls: {}          