apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak
  name: keycloak-lb
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: keycloak-http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: keycloak
  sessionAffinity: None
  type: LoadBalancer