apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: register-virtual-service
spec:
  hosts:
  - register
  gateways:
  - virtual-service-gateway
  http:
  - route:
    - destination:
        host: register
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: register-destination-rule
spec:
  host: register
  subsets:
  - name: v1
    labels:
      version: v1