apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: register-virtual-service
spec:
  hosts:
  - register
  http:
  - match:
    - headers:
        requester-id:
          exact: "c7f226f0-3f97-44ad-9057-60a2db2cf42f"
    route:
    - destination:
        host: register
        subset: v3
  - route:
    - destination:
        host: register
        subset: v1
      weight: 100
    - destination:
        host: register
        subset: v2
      weight: 0
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: register-destination-rule
spec:
  host: register
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  - name: v3
    labels:
      version: v3
      