apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      expose: "true"
      app: acquirer
      group: tech.claudioed
    name: acquirer
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: acquirer
      group: tech.claudioed
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"
      prometheus.io/path: "/actuator/prometheus"
    labels:
      version: v1
      expose: "false"
      app: acquirer
      group: tech.claudioed
    name: acquirer
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: acquirer
        group: tech.claudioed
    template:
      metadata:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "8080"
          prometheus.io/path: "/actuator/prometheus"
        labels:
          app: acquirer
          version: v1
          group: tech.claudioed
      spec:
        containers:       
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: JAEGER_SERVICE_NAME
            value: acquirer            
          - name: JAEGER_ENDPOINT
            value: "http://jaeger-collector.istio-system.svc:14268/api/traces"
          - name: JAEGER_PROPAGATION
            value: b3
          - name: JAEGER_SAMPLER_TYPE
            value: const
          - name: JAEGER_SAMPLER_PARAM
            value: "1"
          - name: MONGO_HOST
            value: mongodb.database.svc.cluster.local
          - name: SERVER_PORT
            value: "8080"
          - name: HTTP_LEVEL_LOGS
            value: "INFO"
          - name: ISSUER_DATA_URL
            value: "http://systems.payments.svc.cluster.local"            
          - name: ISSUER_DATA_PORT
            value: "8080"
          - name: CRM_DATA_URL
            value: "http://systems.payments.svc.cluster.local"
          - name: CRM_DATA_PORT
            value: "8080"
          - name: VAULT_URL
            value: "vault.payments.svc.cluster.local"
          - name: VAULT_PORT
            value: "50051"
          image: claudioed/acquirer:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
          name: acquirer
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
          securityContext:
            privileged: false