apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: claims-virtual-service
spec:
  hosts:
  - claims
  http:
  - route:
    - destination:
        host: claims
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: claims-destination-rule
spec:
  host: claims
  subsets:
  - name: v1
    labels:
      version: v1