apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: payments-virtual-service
spec:
  hosts:
  - payments
  http:
  - route:
    - destination:
        host: payments
        subset: v1
      weight: 100    
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: payments-destination-rule
spec:
  host: payments
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v3
    labels:
      version: v3