apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: crm-virtual-service
spec:
  hosts:
  - crm
  http:
  - route:
    - destination:
        host: crm
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: crm-destination-rule
spec:
  host: crm
  subsets:
  - name: v1
    labels:
      version: v1