apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: systems-virtual-service
spec:
  hosts:
  - systems
  http:
  - route:
    - destination:
        host: systems
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: systems-destination-rule
spec:
  host: systems
  subsets:
  - name: v1
    labels:
      version: v1