---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      expose: "true"
      app: payments-authorization
      group: tech.claudioed
    name: payments-authorization
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: payments-authorization
      group: tech.claudioed
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"
      prometheus.io/path: "/metrics"
    labels:
      version: v1
      expose: "false"
      app: payments-authorization
      group: tech.claudioed
    name: payments-authorization
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: payments-authorization
        group: tech.claudioed
    template:
      metadata:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "8080"
          prometheus.io/path: "/metrics"
        labels:
          app: payments-authorization
          version: v1
          group: tech.claudioed
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MONGO_HOST
            value: mongodb.database.svc.cluster.local
          - name: JAEGER_ENDPOINT
            value: "http://jaeger-collector:14268/api/traces"
          - name: JAEGER_SAMPLER_TYPE
            value: const
          - name: JAEGER_SAMPLER_PARAM
            value: "1"
          image: claudioed/payment-authorization:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
          name: payments-authorization
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
          securityContext:
            privileged: false
