---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      expose: "true"
      app: issuer-one
      group: tech.claudioed
    name: issuer-one
  spec:
    ports:
    - name: grpc
      port: 50051
      protocol: TCP
      targetPort: 50051
    selector:
      app: issuer-one
      group: tech.claudioed
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "50051"
      prometheus.io/path: "/actuator/prometheus"
    labels:
      version: v1
      expose: "false"
      app: issuer-one
      group: tech.claudioed
    name: issuer-one
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: issuer-one
        group: tech.claudioed
    template:
      metadata:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "50051"
          prometheus.io/path: "/actuator/prometheus"
        labels:
          app: issuer-one
          version: v1
          group: tech.claudioed
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: ISSUER_NAME
            value: issuer-one                
          - name: JAEGER_SERVICE_NAME
            value: issuer-one
          - name: MONGO_HOST
            value: mongodb.database.svc.cluster.local
          - name: GRPC_SERVER_PORT
            value: "50051"            
          - name: JAEGER_ENDPOINT
            value: "http://jaeger-collector:14268/api/traces"
          - name: HTTP_LEVEL_LOGS
            value: "INFO"
          - name: NATS_HOST
            value: "nats://10.0.8.118:4222"
          - name: NATS_USER
            value: "nats_client"
          - name: NATS_PASS
            value: "DZ3mFLXEDO"
          - name: VAULT_SERVICE_HOST
            value: "vault.payments.svc.cluster.local"
          - name: VAULT_SERVICE_PORT
            value: "50051"                        
          image: claudioed/issuer:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          name: issuer-one
          ports:
          - containerPort: 50051
            name: grpc
            protocol: TCP
          securityContext:
            privileged: false