apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: facade-virtual-service
spec:
  hosts:
  - facade
  http:
  - route:
    - destination:
        host: facade
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: facade-destination-rule
spec:
  host: facade
  subsets:
  - name: v1
    labels:
      version: v1