apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      expose: "true"
      app: payments
      group: tech.claudioed
      stack: spring
      interface: rest
      language: java            
    name: payments
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: payments
      group: tech.claudioed
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"
      prometheus.io/path: "/actuator/prometheus"
    labels:
      version: v1
      expose: "false"
      app: payments
      group: tech.claudioed
      stack: spring
      interface: rest
      language: java          
    name: payments
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: payments
        group: tech.claudioed
    template:
      metadata:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "8080"
          prometheus.io/path: "/actuator/prometheus"
        labels:
          app: payments
          version: v1
          group: tech.claudioed
          stack: spring
          interface: rest
          language: java              
      spec:
        containers:       
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: JAEGER_SERVICE_NAME
            value: payments        
          - name: JAEGER_ENDPOINT
            value: "http://jaeger-collector.istio-system.svc:14268/api/traces"
          - name: JAEGER_PROPAGATION
            value: b3
          - name: JAEGER_SAMPLER_TYPE
            value: const
          - name: JAEGER_SAMPLER_PARAM
            value: "1"
          - name: MONGO_HOST
            value: mongodb.database.svc.cluster.local
          - name: REGISTER_SVC_URL
            value: http://acquirer:8080
          - name: REQUESTER_SVC_URL
            value: http://payment-checker:8080
          - name: SERVER_PORT
            value: "8080"
          - name: HTTP_LEVEL_LOGS
            value: "INFO"
          - name: NATS_HOST
            value: "nats://10.0.8.118:4222"
          - name: NATS_USER
            value: "nats_client"
          - name: NATS_PASS
            value: "DZ3mFLXEDO"
          - name: CUSTOMER_SERVICE_HOST
            value: customers.payments.svc.cluster.local
          - name: CUSTOMER_SERVICE_PORT
            value: '50051'   
          - name: PAYMENT_AUTH_SVC_URL
            value: http://payments-authorization:8080                  
          image: claudioed/payments:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
          name: payments
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
          securityContext:
            privileged: false  
