apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: payment-checker
spec:
  hosts:
  - "payment-checker"
  http:
  - match:
    - headers:
        requester-id:
          exact: "b9924c5b-6702-47f6-99c5-d2445382fff8"
    fault:
      abort:
        percent: 100
        httpStatus: 500
    route:
    - destination:
        host: payment-checker
        subset: v1
  - route:
    - destination:
        host: payment-checker
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: payment-checker-destination-rule
spec:
  host: payment-checker
  subsets:
  - name: v1
    labels:
      version: v1