apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: payment-checker-virtual-service
spec:
  hosts:
  - payment-checker
  http:
  - route:
    - destination:
        host: payment-checker
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: payment-checker-destination-rule
spec:
  host: payment-checker
  subsets:
  - name: v1
    labels:
      version: v1