---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      expose: "true"
      app: customers
      group: tech.claudioed
      stack: vert.x
      interface: grpc
      language: kotlin      
    name: customers
  spec:
    ports:
    - name: grpc
      port: 50051
      protocol: TCP
      targetPort: 50051
    selector:
      app: customers
      group: tech.claudioed
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      version: v1
      expose: "false"
      app: customers
      group: tech.claudioed
      stack: vert.x
      interface: grpc
      language: kotlin      
    name: customers
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: customers
        group: tech.claudioed
    template:
      metadata:
        labels:
          app: customers
          version: v1
          group: tech.claudioed
          stack: vert.x
          interface: grpc
          language: kotlin                
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: JAEGER_SERVICE_NAME
            value: customers
          - name: MONGO_HOST
            value: "mongodb://mongodb.database.svc.cluster.local:27017"
          image: claudioed/customer:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          name: customers
          resources:
            requests:
              cpu: 128m
              memory: 512Mi
            limits:
              cpu: 256m
              memory: 1024Mi         
          ports:
          - containerPort: 50051
            name: grpc
            protocol: TCP
          securityContext:
            privileged: false
