---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      expose: "true"
      app: facade
      group: tech.claudioed
    name: facade
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: facade
      group: tech.claudioed
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"
      prometheus.io/path: "/actuator/prometheus"
      sidecar.istio.io/rewriteAppHTTPProbers: "true"      
    labels:
      version: v1
      expose: "false"
      app: facade
      group: tech.claudioed
    name: facade
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: facade
        group: tech.claudioed
    template:
      metadata:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "8080"
          prometheus.io/path: "/actuator/prometheus"
          sidecar.istio.io/rewriteAppHTTPProbers: "true"                
        labels:
          app: facade
          version: v1
          group: tech.claudioed
      spec:
        containers:   
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: VAULT_URL
            value: vault.payments-mtls.svc.cluster.local
          - name: VAULT_PORT
            value: "50051"
          - name: ISSUER_URL
            value: issuer-one.payments-mtls.svc.cluster.local            
          - name: ISSUER_PORT
            value: "50051"
          - name: CUSTOMER_URL
            value: customers.payments-mtls.svc.cluster.local
          - name: CUSTOMER_PORT
            value: "50051"
          image: claudioed/facade:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
          name: requesters
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
          securityContext:
            privileged: false