---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      expose: "true"
      app: systems
      group: tech.claudioed
      stack: spring-webflux
      interface: rest
      language: java          
    name: systems
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: systems
      group: tech.claudioed
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"
      prometheus.io/path: "/actuator/prometheus"
      sidecar.istio.io/rewriteAppHTTPProbers: "true"
    labels:
      version: v1
      expose: "false"
      app: systems
      group: tech.claudioed
      stack: spring-webflux
      interface: rest
      language: java          
    name: systems
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: systems
        group: tech.claudioed
    template:
      metadata:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "8080"
          prometheus.io/path: "/actuator/prometheus"
        labels:
          app: systems
          version: v1
          group: tech.claudioed
          stack: spring-webflux
          interface: rest
          language: java             
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: JAEGER_SERVICE_NAME
            value: systems
          - name: MONGO_HOST
            value: mongodb.database.svc.cluster.local
          - name: SERVER_PORT
            value: "8080"
          - name: JAEGER_HTTP_COLLECTOR_URL
            value: "http://jaeger-collector:14268/api/traces"
          - name: HTTP_LEVEL_LOGS
            value: "INFO"                  
          image: claudioed/systems:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
          name: systems
          resources:
            requests:
              cpu: 128m
              memory: 512Mi
            limits:
              cpu: 256m
              memory: 1024Mi
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
          securityContext:
            privileged: false
