apiVersion: "rbac.istio.io/v1alpha1"
kind: RbacConfig
metadata:
  name: default
spec:
  mode: 'ON_WITH_INCLUSION'                     
  inclusion:
    services:
    - "crm.payments-mtls.svc.cluster.local"
    - "customers.payments-mtls.svc.cluster.local" 
    - "issuer-one.payments-mtls.svc.cluster.local"
    - "payment-checker.payments-mtls.svc.cluster.local"
    - "payments.payments-mtls.svc.cluster.local"
    - "systems.payments-mtls.svc.cluster.local"
    - "vault.payments-mtls.svc.cluster.local"