apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fraud-detection-virtual-service
spec:
  hosts:
  - fraud-detection
  http:
  - route:
    - destination:
        host: fraud-detection
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: fraud-detection-destination-rule
spec:
  host: fraud-detection
  subsets:
  - name: v1
    labels:
      version: v1