apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: product-virtual-service
spec:
  hosts:
  - product
  http:
  - route:
    - destination:
        host: product
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: product-destination-rule
spec:
  host: product
  subsets:
  - name: v1
    labels:
      version: v1