---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      expose: "true"
      app: vault
      group: tech.claudioed
      stack: micronaut
      interface: grpc
      language: java         
    name: vault
  spec:
    ports:
    - name: grpc
      port: 50051
      protocol: TCP
      targetPort: 50051
    selector:
      app: vault
      group: tech.claudioed
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      version: v1
      expose: "false"
      app: vault
      group: tech.claudioed
      stack: micronaut
      interface: grpc
      language: java        
    name: vault
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: vault
        group: tech.claudioed
    template:
      metadata:
        labels:
          app: vault
          version: v1
          group: tech.claudioed
          stack: micronaut
          interface: grpc
          language: java            
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: JAEGER_SERVICE_NAME
            value: vault
          image: claudioed/vault:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          name: vault
          ports:
          - containerPort: 50051
            name: grpc
            protocol: TCP
          securityContext:
            privileged: false
